### ISSUE TITLE
Unable to configure keyboard sensor 

### ISSUE THREAD

**Issue by morandanieli** [awareframework/AWARE-Configurator#113]
Keyboard sensor settings is missing in Aware Configurator UI:
![screencapture-configurator-aware-light-org-study-sensor-data-2024-07-01-20_28_24](https://github.com/awareframework/AWARE-Light-Configurator/assets/2284463/5f376c09-5d05-4f27-96cc-2bab4093abce)

**Comment by tinazhang128** [comment]
Hi. The keyboard sensor is included in the Sensor data -> Application -> Keyboard sensor.
