### ISSUE TITLE
create first page in "design your own study"

### ISSUE THREAD

**Issue by yiyanw** [awareframework/AWARE-Configurator#2]
implement the first form of "design your own study", which includes basic information,

 
<img src='https://user-images.githubusercontent.com/31875861/184641527-d0af7171-9f95-4949-893b-4523aa2cf090.png' width=500/>

 and database information.

<img src='https://user-images.githubusercontent.com/31875861/184641587-e80e4fc0-974a-4c39-86e1-a57086d757d7.png' width=500/>

Material UI provides [textField](https://mui.com/material-ui/react-text-field/#form-props) component to make a form. 
Please keep the database testing function empty and mark it as "//todo"

**Comment by tinazhang128** [comment]
First page created: sidebar + survey for StudyInformation. UI interface initialised. Backend actions not set.
