### ISSUE TITLE
DB and INSERT user initialization message

### ISSUE THREAD

**Issue by simonjd** [awareframework/AWARE-Configurator#27]
I was able to successfully initialize a DB and INSERT user with the existing configurator, however the message at the bottom of the file included below incorrectly implies that something went wrong. Could this be because my admin account is 'root2' instead of 'root', and that the configurator message is triggered by a strict check for only accepting 'root' as the admin username?

![image](https://user-images.githubusercontent.com/3935545/193443144-e7ef31a8-2d28-4b80-8b10-4ea62c196994.png)

**Comment by tinazhang128** [comment]
Hello Dr D'Alfonso. This is a bug of the previous repository. We are aware of that and will make changes in the Django one.

**Comment by tinazhang128** [comment]
Bug fixed in the Django versions.
