### ISSUE TITLE
create side nav bar

### ISSUE THREAD

**Issue by yiyanw** [awareframework/AWARE-Configurator#3]
create a side nav bar for "design your own study"

[stepper](https://mui.com/material-ui/react-stepper/) or [drawer](https://mui.com/material-ui/react-drawer/) can be a good choice for side nav bar.

<img src='https://user-images.githubusercontent.com/31875861/184643328-a86dc401-3081-4cf1-95c5-ffdb301f41a8.png' width=500/>

<img src='https://user-images.githubusercontent.com/31875861/184643469-16ce2914-b0fe-4f31-bba9-c17c2e20696f.png' width=500/>

**Comment by tinazhang128** [comment]
Sidebar created in a folder called components.

**Comment by yiyanw** [comment]
@tinazhang128  I think there is a bug in the sidebar.
When I click another stage in the new study creation, the blue square will not follow.

for example, I click "Questions" button, but the blue square does not move to this button.
<img src='https://user-images.githubusercontent.com/31875861/187019514-56ddce46-8341-4be3-af86-fd9432d03608.png' width=300/>

**Comment by yiyanw** [comment]
> @tinazhang128 I think there is a bug in the sidebar. When I click another stage in the new study creation, the blue square will not follow.
> 
> for example, I click "Questions" button, but the blue square does not move to this button. <img alt="" width="300/" src="https://user-images.githubusercontent.com/31875861/187019514-56ddce46-8341-4be3-af86-fd9432d03608.png">

fixed
