### ISSUE TITLE
some buttons does not works in the sensor page

### ISSUE THREAD

**Issue by yiyanw** [awareframework/AWARE-Configurator#39]
![image](https://user-images.githubusercontent.com/31875861/198882874-1a0618bb-6afb-46bd-8c79-b88fdac135a1.png)
![image](https://user-images.githubusercontent.com/31875861/198882888-c1bd0b85-b7f2-424f-b4fd-bbca2481926c.png)
![image](https://user-images.githubusercontent.com/31875861/198882905-95897c9e-422d-400d-8d21-2d4ca4308f2b.png)

**Comment by tinazhang128** [comment]
Bugs fixed in sensor data page.
