### ISSUE TITLE
Strict Next Step Button on First Page

### ISSUE THREAD

**Issue by simonjd** [awareframework/AWARE-Configurator#42]
I have an existing DB and INSERT-only user, so did not fill in the root details. When I went to press the Next button on the first page, I received the following message:

![image](https://user-images.githubusercontent.com/3935545/199393692-3b0bbdf8-ca7e-4ffb-acb8-3487f0d7a3ef.png)

**Comment by tinazhang128** [comment]
Bug fixed for the study information page.
