### ISSUE TITLE
AWARE-LIGHT CONFIGURATION PAGE

### ISSUE THREAD

**Issue by simonjd** [awareframework/AWARE-Configurator#43]
Rename this to "AWARE-Light Configurator".

Also, make the font size larger, like 24pt or something.

![image](https://user-images.githubusercontent.com/3935545/199395522-34fa97ad-72f9-452f-9626-7a28cd2fd57e.png)

**Comment by tinazhang128** [comment]
Font size adjusted to 24pt.
