### ISSUE TITLE
Small adjustment to do (not urgent)

### ISSUE THREAD

**Issue by simonjd** [awareframework/AWARE-Configurator#71]
Hi. Could we please replace "React App" in the HTML title with "AWARE-Light Configurator".

<title>React App</title>

**Comment by tinazhang128** [comment]
Hi Simon. Where does this "React App" come from?

**Comment by simonjd** [comment]
![image](https://user-images.githubusercontent.com/3935545/212670038-e837651e-de2a-4330-a674-7638b97e2ea1.png)

**Comment by simonjd** [comment]
It is the HTML title. You can see it appear in tabs and such. For example, I highlighted it in a red box in the image above.

**Comment by tinazhang128** [comment]
Cool, all done and deployed.
