### ISSUE TITLE
Add a Note below INITIALISE DATABASE button.

### ISSUE THREAD

**Issue by simonjd** [awareframework/AWARE-Configurator#72]
> Note: if INITIALISE DATABASE is failing despite correct root credentials, (1) make sure port 3306 is open and (2) if your DB enforces an SSL connection, temporarily turn it off while using the configurator.

![image](https://user-images.githubusercontent.com/3935545/212685636-06f97ac2-9a0f-476b-9956-e19e474bdd38.png)

**Comment by tinazhang128** [comment]
Note added.
