### ISSUE TITLE
QUESTION- validation check for new study creation

### ISSUE THREAD

**Issue by yiyanw** [awareframework/AWARE-Configurator#9]
I saw we used a validation check on every page of new study creation. Users cannot go to the next page if they do not input valid information. 
here is an example:
<img src='https://user-images.githubusercontent.com/31875861/187022677-0e63eaae-572d-4b37-9da5-654e7d0493fe.png' width=400/>

@tinazhang128 do you have any idea about it?

**Comment by tinazhang128** [comment]
Hi, Yiyan. For this part I think we should not create a new logic from the original logic.

The original logic: not allowing to go to the next page if not filled in or not validated. This brings the problem that the questions cannot be browsed but harshly needs to be filled in.

I think we should have this new logic: 
1. the question can be blank until the final Overview page;
2. save buttons should be provided in each survey page;
3. users are able to go back directly to the fields that are not validated or not filled from the overview

Hi, Dr. D'lAfonso @simonjd 
Do you agree or disagree? Do you have any suggestions?
